spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root
    data-password: 123456
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wxacc3c0f3250e5e0a
  mpAppSecret: 31e522af216a169757f259a2e1c2f7d8
  mchId: 1409146202
  mcnKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cer/h5.p12
  notifyUrl: http://chub.natapp1.cc/sell/pay/notify #异步通知



